### PR TITLE
Fix Dbnary data loading on Windows

### PR DESCRIPTION
**Pull request by Vuizur**
I could build the pl-pl database now, it looked reasonable.

### CODE REVIEW

**Comment by xxyzz** [comment]
If you could install wget and perl, why not install the compress tools? They use threads and are way faster.

**Comment by Vuizur** [comment]
I mostly did not use them because they are not on Winget. I couldn't find the unzip command line programs on chocolatey either.

**Comment by xxyzz** [comment]
Sorry I removed the winget commands... I expect the users could figure out the dependencies. And I feel it's inappropriate to add commands install unofficial packages.

**Comment by Vuizur** [comment]
Winget downloads the executables from the official places, so it is not a
random .exe (like on Chocolatey). Imo it's the best we have, although I
feel that they are pretty understaffed by Microsoft.

Am Do., 22. Feb. 2024 um 11:08 Uhr schrieb xxyzz ***@***.***>:

**Comment by xxyzz** [comment]
I think Winget also downloads .exe files from other places: https://github.com/microsoft/winget-pkgs/blob/master/manifests/j/JernejSimoncic/Wget/1.21.4/JernejSimoncic.Wget.installer.yaml

But it doesn't matter... There are too many ways to install packages, so I'll just list the dependencies and let users decide how to install them.

**Pull request merged**
